// <auto-generated />
using EfCrudCalisma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCrudCalisma.Data.Migrations
{
    [DbContext(typeof(SozlukContext))]
    partial class SozlukContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfCrudCalisma.Data.Girdi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anlam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sozcuk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Girdiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anlam = "Kitap",
                            Sozcuk = "Book"
                        },
                        new
                        {
                            Id = 2,
                            Anlam = "Bilgisayar",
                            Sozcuk = "Computer"
                        },
                        new
                        {
                            Id = 3,
                            Anlam = "Güneş",
                            Sozcuk = "Sun"
                        },
                        new
                        {
                            Id = 4,
                            Anlam = "Araba",
                            Sozcuk = "Car"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
